---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: petclinic-mysql
  namespace: default
data:
  MYSQL_DATABASE: cGV0Y2xpbmlj
  MYSQL_ROOT_PASSWORD: cGV0Y2xpbmlj
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: petclinic
  namespace: default
data:
  BASE_IMAGE: cmF5c2hvby9wZXRjbGluaWMtYmFzZQ==
  BASE_IMAGE_TAG: bGF0ZXN0
  WAS_IMAGE: cmF5c2hvby9wZXRjbGluaWM=
  WAS_IMAGE_TAG: djEuMC4wLWFscGhh
  MYSQL_URL: cGV0Y2xpbmljLW15c3Fs
  MYSQL_PORT: MzMwNg==
  MYSQL_USER: cm9vdA==
  MYSQL_PASS: cGV0Y2xpbmlj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-mysql
  name: petclinic-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-mysql
  template:
    metadata:
      labels:
        app: petclinic-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        envFrom:
        - secretRef:
            name: petclinic-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: rayshoo/petclinic:v1.0.0-alpha
        name: petclinic
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: petclinic-mysql
              key: MYSQL_DATABASE
        envFrom:
        - secretRef:
            name: petclinic
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-mysql
  name: petclinic-mysql
  namespace: default
spec:
  # type: ClusterIP
  # clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: petclinic-mysql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic
  name: petclinic
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic
            port:
              number: 8080
