server:
  port: ${WAS_PORT:8080}
  shutdown: graceful
spring:
  # sigkill timeout
  lifecycle:
    timeout-per-shutdown-phase: 30s
  # set profile
  profiles:
    active: ${SPRING_PROFILE:local}
  # database init
  datasource:
    username: ${MYSQL_USER:root}
    url: jdbc:mysql://${MYSQL_URL:petclinic-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:petclinic}
    password: ${MYSQL_PASS}
  # do not attempt to replace database with in-memory database
  test:
    database:
      replace: none
  # Internationalization
  messages:
    basename: messages/messages
  # Maximum time static resources should be cached
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 12h
# Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          DOWN: 503
          OUT_OF_SERVICE: 503
          UNKNOWN: 200
          UP: 200
        order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
# Logging
logging:
  level:
    org:
      springframework: info
    sql: debug
