---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-mysql
  name: petclinic-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-mysql
  template:
    metadata:
      labels:
        app: petclinic-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        envFrom:
        - secretRef:
            name: petclinic-mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: petclinic