---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-mysql
  name: petclinic-mysql
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: petclinic-mysql